### PR TITLE
US_7 Tuya

### PR DESCRIPTION
**Pull request by Tuyasht**
US_7 Tuya

### CODE REVIEW

**Comment by Kms2127** [comment]
Great job Tuya.

**Comment by Tuyasht** [comment]
Thank you,

**Review by aykhanakhundov — COMMENTED** [review]
Your code looks great

**Comment by AliAras20** [comment]
Awesome

**Review by AliAras20 — COMMENTED** [review]
Great!

**Review by AliAras20 — APPROVED** [review]

**Pull request merged**
